/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AtskaHeart (https://sketchfab.com/atskaheart)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pixel-car-1bb69bbe51fc4e11ad10ea80c32ca7f6
title: Pixel car
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/PixelCar/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane_0" />
              <group name="Car_6" position={[0, 0.03, 0.48]}>
                <group name="BackDoorsRight_2" position={[-0.7, 1.49, 0.17]}>
                  <group name="BackDoorsGlass_1" position={[0, -0.03, 0]}>
                    <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material} />
                  </group>
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.TexturePaint} />
                </group>
                <group name="CarGlass_3" position={[0, 1.48, 0.06]}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material} />
                </group>
                <group name="FrontalDoorsRight_5" position={[-0.75, 0.91, 1.02]}>
                  <group name="FrontalDoorsGlass001_4" position={[0.08, 0.35, -0.11]}>
                    <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material} />
                  </group>
                  <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.TexturePaint} />
                </group>
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.TexturePaint} />
              </group>
              <group name="BackDoorsLeft_8" position={[0.75, 1.52, 0.64]}>
                <group name="BackDoorsGlass001_7" position={[0, -0.03, 0]}>
                  <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Material} />
                </group>
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.TexturePaint} />
              </group>
              <group name="BackLeft_Wheel_9" position={[0.61, 0.3, -0.24]} rotation={[0.5, 0, 0]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.TexturePaint} />
              </group>
              <group name="BackRight_Wheel_10" position={[-0.61, 0.3, -0.24]} rotation={[0.5, 0, 0]}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.TexturePaint} />
              </group>
              <group name="Car_antenna_11" position={[0.17, 1.57, -0.33]} rotation={[3.14, 0.39, -3.14]}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.TexturePaint} />
              </group>
              <group name="Car_control_12" position={[0.4, 0.92, 1.23]} rotation={[0, 0, 0]}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.TexturePaint} />
              </group>
              <group name="Car_front_13" position={[0, 1.01, 1.59]} rotation={[-Math.PI, 0.39, -Math.PI]}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.TexturePaint} />
              </group>
              <group name="Car_peacesymbol_14" position={[0, 1.39, 1.21]} rotation={[-3.14, 0.39, 3.14]}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.TexturePaint} />
              </group>
              <group name="Car_plate_15" position={[0, 0.43, 2.27]} rotation={[-Math.PI, 0.39, -Math.PI]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.TexturePaint} />
              </group>
              <group name="FrontalDoorsLeft_17" position={[0.75, 0.94, 1.5]}>
                <group name="FrontalDoorsGlass_16" position={[-0.08, 0.35, -0.11]}>
                  <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Material} />
                </group>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.TexturePaint} />
              </group>
              <group name="FrontLeft_Wheel_18" position={[0.61, 0.3, 1.78]} rotation={[0.5, 0, 0]}>
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.TexturePaint} />
              </group>
              <group name="FrontRight_Wheel_19" position={[-0.61, 0.3, 1.78]} rotation={[0.5, 0, 0]}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.TexturePaint} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/PixelCar/scene.gltf')
